export type Shortcut = {
  key: string;
  desc: string;
};

export const SHORTCUTS: Shortcut[] = [
  { key: 'Enter', desc: 'new sibling' },
  { key: 'Tab', desc: 'new child' },
  { key: 'Shift+Tab', desc: 'promote node' },
  { key: 'Delete', desc: 'delete selected node(s)' },
  { key: 'Cmd/Ctrl+Z', desc: 'undo' },
  { key: 'Cmd/Ctrl+Shift+Z / Cmd/Ctrl+Y', desc: 'redo' },
  { key: 'Cmd/Ctrl+K', desc: 'toggle search dialog' },
  { key: 'Search: Tab / Shift+Tab', desc: 'cycle active result selection' },
  { key: 'Search: PageUp / PageDown', desc: 'jump active result by 5 items' },
  { key: 'Search: Home / End', desc: 'jump to first/last search result' },
  { key: 'Search: Shift/Cmd/Ctrl/Alt+Enter or click', desc: 'jump to result and keep search dialog open' },
  { key: 'Search: Esc', desc: 'clear query (or close dialog when query is empty)' },
  { key: 'Search: Cmd/Ctrl+Shift+K', desc: 'clear query and keep search dialog open' },
  { key: 'Search: Cmd/Ctrl+F', desc: 'focus search input' },
  { key: 'Search: Cmd/Ctrl+A', desc: 'select search input text' },
  { key: 'Help: Esc', desc: 'clear filter (or close dialog when filter is empty)' },
  { key: 'Help: Cmd/Ctrl+Shift+K', desc: 'clear filter and keep help dialog open' },
  { key: 'Help: Cmd/Ctrl+F', desc: 'focus help filter input' },
  { key: 'Help: Cmd/Ctrl+A', desc: 'select help filter input text' },
  { key: 'Cmd/Ctrl+S', desc: 'export JSON' },
  { key: 'Cmd/Ctrl+Shift+S', desc: 'export PNG' },
  { key: 'Cmd/Ctrl+Shift+M', desc: 'export Markdown' },
  { key: 'Cmd/Ctrl+Shift+C', desc: 'copy selected/focused node text' },
  { key: 'Cmd/Ctrl+Shift+L', desc: 'copy focused subtree outline' },
  { key: 'Cmd/Ctrl+click', desc: 'multi-select nodes' },
  { key: 'Cmd/Ctrl+A', desc: 'select all nodes' },
  { key: 'Alt+I', desc: 'invert selection' },
  { key: 'Cmd/Ctrl+B', desc: 'bold text (in edit mode)' },
  { key: 'Cmd/Ctrl+I', desc: 'italicize text (in edit mode)' },
  { key: 'Cmd/Ctrl+Shift+8', desc: 'bullet list (in edit mode)' },
  { key: 'Cmd/Ctrl+Shift+7', desc: 'numbered list (in edit mode)' },
  { key: 'Cmd/Ctrl+D', desc: 'duplicate selected node(s)' },
  { key: 'Alt+S', desc: 'select siblings of focused node' },
  { key: 'Alt+C', desc: 'select children of focused node' },
  { key: 'Alt+L', desc: 'select leaves under focused subtree' },
  { key: 'Alt+U', desc: 'select ancestors of focused node' },
  { key: 'Alt+T', desc: 'reduce selection to top-level nodes' },
  { key: 'Alt+G', desc: 'select nodes at focused depth level' },
  { key: 'Alt+X', desc: 'clear selection extras (keep focus)' },
  { key: 'Alt+N', desc: 'expand selection to parents + children' },
  { key: 'Alt+Shift+X', desc: 'align selected nodes to focused X' },
  { key: 'Alt+Shift+Y', desc: 'align selected nodes to focused Y' },
  { key: 'Alt+Shift+H', desc: 'distribute selected nodes horizontally' },
  { key: 'Alt+Shift+V', desc: 'distribute selected nodes vertically' },
  { key: 'Alt+Shift+R', desc: 'layout selected nodes into a row' },
  { key: 'Alt+Shift+D', desc: 'layout selected nodes into a column' },
  { key: 'Alt+Shift+G', desc: 'snap selected nodes to 20px grid' },
  { key: 'Alt+Shift+M', desc: 'mirror selected nodes across focused X axis' },
  { key: 'Alt+Shift+W', desc: 'mirror selected nodes across focused Y axis' },
  { key: 'Alt+[', desc: 'stack selected nodes along X from focus' },
  { key: 'Alt+]', desc: 'stack selected nodes along Y from focus' },
  { key: 'Alt+B', desc: 'select focused subtree' },
  { key: 'Alt+Shift+B', desc: 'center focused subtree' },
  { key: 'Alt+P', desc: 'select parent of focused node' },
  { key: 'Alt+Shift+P', desc: 'copy focused node path' },
  { key: 'E / double‑click', desc: 'edit node' },
  { key: 'Arrow keys', desc: 'move focus' },
  { key: 'Mini-map: Arrow keys', desc: 'pan mini-map viewport when mini-map is focused' },
  { key: 'Mini-map: Shift+Arrow', desc: 'pan mini-map viewport faster when mini-map is focused' },
  { key: 'Mini-map: PageUp / PageDown', desc: 'pan mini-map viewport vertically by large steps when mini-map is focused' },
  { key: 'Mini-map: Shift+PageUp / Shift+PageDown', desc: 'pan mini-map viewport horizontally by large steps when mini-map is focused' },
  { key: 'Mini-map: Home / End', desc: 'jump mini-map viewport to map edges when mini-map is focused' },
  { key: 'Shift+Arrow', desc: 'nudge selected node(s) by configurable distance' },
  { key: 'Shift+Alt+Arrow', desc: 'nudge selected node(s) by configurable large distance' },
  { key: 'F', desc: 'fit to view' },
  { key: 'Alt+F', desc: 'fit selected nodes' },
  { key: 'Alt+Shift+F', desc: 'fit focused subtree' },
  { key: 'Shift+G', desc: 'toggle grid overlay' },
  { key: 'Shift+M', desc: 'toggle mini-map visibility' },
  { key: 'Shift+A', desc: 'toggle advanced toolbar actions' },
  { key: 'Shift+T', desc: 'toggle light/dark theme' },
  { key: 'C', desc: 'center focused node' },
  { key: 'Alt+Shift+C', desc: 'center selected nodes' },
  { key: 'Shift+C', desc: 'center root node' },
  { key: 'R', desc: 'focus + center root node' },
  { key: 'Shift+R', desc: 'focus history forward' },
  { key: 'Alt+Shift+Home', desc: 'jump to oldest focus history entry' },
  { key: 'Alt+Shift+End', desc: 'jump to newest focus history entry' },
  { key: 'Alt+Shift+Q', desc: 'reset focus history to current node' },
  { key: 'Shift+P', desc: 'focus + center parent node' },
  { key: 'Shift+N', desc: 'focus + center first child node' },
  { key: 'Shift+H', desc: 'focus + center previous sibling' },
  { key: 'Shift+J', desc: 'focus + center next sibling' },
  { key: 'Shift+L', desc: 'focus + center first leaf in subtree' },
  { key: 'Shift+K', desc: 'focus + center last leaf in subtree' },
  { key: 'Shift+,', desc: 'focus + center previous leaf in subtree' },
  { key: 'Shift+.', desc: 'focus + center next leaf in subtree' },
  { key: 'Alt+R', desc: 'jump back to previous focus' },
  { key: 'L', desc: 'cycle layout mode (tree ↔ radial ↔ force) + apply auto‑layout' },
  { key: 'Shift+drag', desc: 'pan' },
  { key: 'Ctrl/Cmd+wheel', desc: 'zoom' },
  { key: '=/+', desc: 'zoom in by configurable factor' },
  { key: '-', desc: 'zoom out by configurable factor' },
  { key: '0', desc: 'reset pan/zoom view' },
  { key: 'Cmd/Ctrl+1', desc: 'apply color preset 1 (Default)' },
  { key: 'Cmd/Ctrl+2', desc: 'apply color preset 2 (Primary)' },
  { key: 'Cmd/Ctrl+3', desc: 'apply color preset 3 (Success)' },
  { key: 'Cmd/Ctrl+4', desc: 'apply color preset 4 (Warning)' },
  { key: 'Cmd/Ctrl+5', desc: 'apply color preset 5 (Danger)' },
  { key: 'Cmd/Ctrl+6', desc: 'apply color preset 6 (Info)' },
  { key: 'Cmd/Ctrl+7', desc: 'apply color preset 7 (Muted)' },
  { key: 'Cmd/Ctrl+0', desc: 'reset node style to default' },
  { key: 'Cmd/Ctrl+Shift+R', desc: 'reset node style to default' },
  { key: 'Cmd/Ctrl+T', desc: 'open tag picker dialog' },
  { key: 'Cmd/Ctrl+Shift+T', desc: 'open tag picker dialog' },
  { key: 'Cmd/Ctrl+Shift+F', desc: 'toggle tag filter panel' },
  { key: '?', desc: 'toggle help dialog' },
];

export const FOCUS_NAV_HISTORY_SHORTCUT_KEYS: string[] = [
  'Shift+P',
  'Shift+N',
  'Shift+H',
  'Shift+J',
  'Shift+L',
  'Shift+K',
  'Shift+,',
  'Shift+.',
  'R',
  'Alt+R',
  'Shift+R',
  'Alt+Shift+Home',
  'Alt+Shift+End',
  'Alt+Shift+Q',
];

export function pickShortcutsByKeys(shortcuts: Shortcut[], keys: string[]): Shortcut[] {
  const map = new Map(shortcuts.map(shortcut => [shortcut.key, shortcut]));
  return keys
    .map(key => map.get(key))
    .filter((shortcut): shortcut is Shortcut => !!shortcut);
}

export type TutorialSection = {
  title: string;
  items: { text: string }[];
};

export const TAG_TUTORIAL: TutorialSection[] = [
  {
    title: 'Tag Basics',
    items: [
      { text: 'Click the tag icon on a node to add/edit tags' },
      { text: 'Type a tag name and press Enter to add it' },
      { text: 'Press Backspace on an empty tag field to remove the last tag' },
      { text: 'Existing tags are shown in the autocomplete dropdown' },
      { text: 'Tags appear as colored badges below the node text' },
    ],
  },
  {
    title: 'Bulk Tagging',
    items: [
      { text: 'Select multiple nodes with Cmd/Ctrl+click' },
      { text: 'Press Cmd/Ctrl+T to open the tag picker for selection' },
      { text: 'Check or uncheck tags to apply them to all selected nodes' },
    ],
  },
  {
    title: 'Filtering by Tags',
    items: [
      { text: 'Press Cmd/Ctrl+Shift+F to open the tag filter panel' },
      { text: 'Click a tag in the panel to filter — matching nodes stay visible' },
      { text: 'Non-matching nodes fade to 20% opacity' },
      { text: 'Use "Any" mode: show nodes with any of the selected tags' },
      { text: 'Use "All" mode: show only nodes with all selected tags' },
      { text: 'Click × on a filter chip to remove that tag filter' },
      { text: 'Filter by typing in the panel search field' },
    ],
  },
  {
    title: 'Keyboard Shortcuts',
    items: [
      { text: 'Cmd/Ctrl+T — open tag picker dialog' },
      { text: 'Cmd/Ctrl+Shift+T — open tag picker dialog (alternative)' },
      { text: 'Cmd/Ctrl+Shift+F — toggle tag filter panel' },
    ],
  },
];
