export type Shortcut = {
  key: string;
  desc: string;
};

export const SHORTCUTS: Shortcut[] = [
  { key: 'Enter', desc: 'new sibling' },
  { key: 'Tab', desc: 'new child' },
  { key: 'Shift+Tab', desc: 'promote node' },
  { key: 'Delete', desc: 'delete selected node(s)' },
  { key: 'Cmd/Ctrl+Z', desc: 'undo' },
  { key: 'Cmd/Ctrl+Shift+Z / Cmd/Ctrl+Y', desc: 'redo' },
  { key: 'Cmd/Ctrl+K', desc: 'toggle search dialog' },
  { key: 'Search: Tab / Shift+Tab', desc: 'cycle active result selection' },
  { key: 'Search: PageUp / PageDown', desc: 'jump active result by 5 items' },
  { key: 'Search: Home / End', desc: 'jump to first/last search result' },
  { key: 'Search: Shift/Cmd/Ctrl/Alt+Enter or click', desc: 'jump to result and keep search dialog open' },
  { key: 'Search: Esc', desc: 'clear query (or close dialog when query is empty)' },
  { key: 'Search: Cmd/Ctrl+Shift+K', desc: 'clear query and keep search dialog open' },
  { key: 'Help: Esc', desc: 'clear filter (or close dialog when filter is empty)' },
  { key: 'Help: Cmd/Ctrl+Shift+K', desc: 'clear filter and keep help dialog open' },
  { key: 'Help: Cmd/Ctrl+F', desc: 'focus help filter input' },
  { key: 'Cmd/Ctrl+S', desc: 'export JSON' },
  { key: 'Cmd/Ctrl+Shift+S', desc: 'export PNG' },
  { key: 'Cmd/Ctrl+Shift+M', desc: 'export Markdown' },
  { key: 'Cmd/Ctrl+Shift+C', desc: 'copy selected/focused node text' },
  { key: 'Cmd/Ctrl+Shift+L', desc: 'copy focused subtree outline' },
  { key: 'Cmd/Ctrl+click', desc: 'multi-select nodes' },
  { key: 'Cmd/Ctrl+A', desc: 'select all nodes' },
  { key: 'Alt+I', desc: 'invert selection' },
  { key: 'Cmd/Ctrl+D', desc: 'duplicate selected node(s)' },
  { key: 'Alt+S', desc: 'select siblings of focused node' },
  { key: 'Alt+C', desc: 'select children of focused node' },
  { key: 'Alt+L', desc: 'select leaves under focused subtree' },
  { key: 'Alt+U', desc: 'select ancestors of focused node' },
  { key: 'Alt+T', desc: 'reduce selection to top-level nodes' },
  { key: 'Alt+G', desc: 'select nodes at focused depth level' },
  { key: 'Alt+X', desc: 'clear selection extras (keep focus)' },
  { key: 'Alt+N', desc: 'expand selection to parents + children' },
  { key: 'Alt+Shift+X', desc: 'align selected nodes to focused X' },
  { key: 'Alt+Shift+Y', desc: 'align selected nodes to focused Y' },
  { key: 'Alt+Shift+H', desc: 'distribute selected nodes horizontally' },
  { key: 'Alt+Shift+V', desc: 'distribute selected nodes vertically' },
  { key: 'Alt+Shift+R', desc: 'layout selected nodes into a row' },
  { key: 'Alt+Shift+D', desc: 'layout selected nodes into a column' },
  { key: 'Alt+Shift+G', desc: 'snap selected nodes to 20px grid' },
  { key: 'Alt+Shift+M', desc: 'mirror selected nodes across focused X axis' },
  { key: 'Alt+Shift+W', desc: 'mirror selected nodes across focused Y axis' },
  { key: 'Alt+[', desc: 'stack selected nodes along X from focus' },
  { key: 'Alt+]', desc: 'stack selected nodes along Y from focus' },
  { key: 'Alt+B', desc: 'select focused subtree' },
  { key: 'Alt+Shift+B', desc: 'center focused subtree' },
  { key: 'Alt+P', desc: 'select parent of focused node' },
  { key: 'Alt+Shift+P', desc: 'copy focused node path' },
  { key: 'E / double‑click', desc: 'edit node' },
  { key: 'Arrow keys', desc: 'move focus' },
  { key: 'Mini-map: Arrow keys', desc: 'pan mini-map viewport when mini-map is focused' },
  { key: 'Mini-map: Shift+Arrow', desc: 'pan mini-map viewport faster when mini-map is focused' },
  { key: 'Mini-map: PageUp / PageDown', desc: 'pan mini-map viewport vertically by large steps when mini-map is focused' },
  { key: 'Mini-map: Shift+PageUp / Shift+PageDown', desc: 'pan mini-map viewport horizontally by large steps when mini-map is focused' },
  { key: 'Mini-map: Home / End', desc: 'jump mini-map viewport to map edges when mini-map is focused' },
  { key: 'Alt+Arrow', desc: 'nudge selected node(s) by 10px' },
  { key: 'Shift+Alt+Arrow', desc: 'nudge selected node(s) by 40px' },
  { key: 'F', desc: 'fit to view' },
  { key: 'Alt+F', desc: 'fit selected nodes' },
  { key: 'Alt+Shift+F', desc: 'fit focused subtree' },
  { key: 'Shift+G', desc: 'toggle grid overlay' },
  { key: 'Shift+M', desc: 'toggle mini-map visibility' },
  { key: 'Shift+A', desc: 'toggle advanced toolbar actions' },
  { key: 'C', desc: 'center focused node' },
  { key: 'Alt+Shift+C', desc: 'center selected nodes' },
  { key: 'Shift+C', desc: 'center root node' },
  { key: 'R', desc: 'focus + center root node' },
  { key: 'Shift+R', desc: 'focus history forward' },
  { key: 'Alt+Shift+Home', desc: 'jump to oldest focus history entry' },
  { key: 'Alt+Shift+End', desc: 'jump to newest focus history entry' },
  { key: 'Alt+Shift+Q', desc: 'reset focus history to current node' },
  { key: 'Shift+P', desc: 'focus + center parent node' },
  { key: 'Shift+N', desc: 'focus + center first child node' },
  { key: 'Shift+H', desc: 'focus + center previous sibling' },
  { key: 'Shift+J', desc: 'focus + center next sibling' },
  { key: 'Shift+L', desc: 'focus + center first leaf in subtree' },
  { key: 'Shift+K', desc: 'focus + center last leaf in subtree' },
  { key: 'Shift+,', desc: 'focus + center previous leaf in subtree' },
  { key: 'Shift+.', desc: 'focus + center next leaf in subtree' },
  { key: 'Alt+R', desc: 'jump back to previous focus' },
  { key: 'L', desc: 'auto‑layout children' },
  { key: 'Shift+drag', desc: 'pan' },
  { key: 'Ctrl/Cmd+wheel', desc: 'zoom' },
  { key: '=/+', desc: 'zoom in' },
  { key: '-', desc: 'zoom out' },
  { key: '0', desc: 'reset pan/zoom view' },
  { key: '?', desc: 'toggle help dialog' },
  { key: 'Cmd/Ctrl+/', desc: 'toggle help dialog' }
];

export const FOCUS_NAV_HISTORY_SHORTCUT_KEYS: string[] = [
  'Shift+P',
  'Shift+N',
  'Shift+H',
  'Shift+J',
  'Shift+L',
  'Shift+K',
  'Shift+,',
  'Shift+.',
  'R',
  'Alt+R',
  'Shift+R',
  'Alt+Shift+Home',
  'Alt+Shift+End',
  'Alt+Shift+Q',
];

export function pickShortcutsByKeys(shortcuts: Shortcut[], keys: string[]): Shortcut[] {
  const map = new Map(shortcuts.map(shortcut => [shortcut.key, shortcut]));
  return keys
    .map(key => map.get(key))
    .filter((shortcut): shortcut is Shortcut => !!shortcut);
}
