export const SHORTCUTS = [
  { key: 'Enter', desc: 'new sibling' },
  { key: 'Tab', desc: 'new child' },
  { key: 'Shift+Tab', desc: 'promote node' },
  { key: 'Delete', desc: 'delete selected node(s)' },
  { key: 'Cmd/Ctrl+Z', desc: 'undo' },
  { key: 'Cmd/Ctrl+Shift+Z / Cmd/Ctrl+Y', desc: 'redo' },
  { key: 'Cmd/Ctrl+K', desc: 'search' },
  { key: 'Cmd/Ctrl+S', desc: 'export JSON' },
  { key: 'Cmd/Ctrl+Shift+S', desc: 'export PNG' },
  { key: 'Cmd/Ctrl+Shift+M', desc: 'export Markdown' },
  { key: 'Cmd/Ctrl+click', desc: 'multi-select nodes' },
  { key: 'Cmd/Ctrl+A', desc: 'select all nodes' },
  { key: 'Alt+I', desc: 'invert selection' },
  { key: 'Cmd/Ctrl+D', desc: 'duplicate selected node(s)' },
  { key: 'Alt+S', desc: 'select siblings of focused node' },
  { key: 'Alt+C', desc: 'select children of focused node' },
  { key: 'Alt+B', desc: 'select focused subtree' },
  { key: 'Alt+P', desc: 'select parent of focused node' },
  { key: 'E / double‑click', desc: 'edit node' },
  { key: 'Arrow keys', desc: 'move focus' },
  { key: 'Alt+Arrow', desc: 'nudge selected node(s) by 10px' },
  { key: 'Shift+Alt+Arrow', desc: 'nudge selected node(s) by 40px' },
  { key: 'F', desc: 'fit to view' },
  { key: 'C', desc: 'center focused node' },
  { key: 'L', desc: 'auto‑layout children' },
  { key: 'Shift+drag', desc: 'pan' },
  { key: 'Ctrl/Cmd+wheel', desc: 'zoom' },
  { key: '?', desc: 'help' }
];
